//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myApp1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int notesID { get; set; }
        public string title { get; set; }
        public string note1 { get; set; }
        public Nullable<int> createdOn { get; set; }
        public Nullable<int> categoryID { get; set; }
        public string isDeleted { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
    }
}
